// Generated by scripts/build.mjs for this deployment. To change settings edit the source js/config.js or the build script.
window.GAME_NIGHT_CONFIG = {
  "env": "dev",
  "build": "20261009.1052-c76dddc",
  "prefix": "gnight-dev-v1-"
};
