// Game registry. Each entry describes a game for the home screen & lobby and lazy-loads its code.
// To add a game: create js/games/<id>.js exporting `start(api)` and add an entry here.

export const CATEGORIES = ['Party', 'Drawing', 'Words', 'Bluffing', 'Cards', 'Strategy', 'Board', 'Arcade', 'Retro', 'Hangout'];

export const GAMES = [
  {
    id: 'sketch',
    name: 'Sketch & Guess',
    emoji: '🎨',
    color: '#ff7a59',
    cat: 'Drawing',
    tags: ['Drawing', 'Words'],
    min: 2,
    max: 12,
    tagline: 'Draw it. Guess it. Win it.',
    desc: 'Take turns drawing a secret word while everyone else races to guess it. The faster you guess, the more points you get — and the drawer scores when people guess right.',
    howto: [
      'On your turn, pick one of three words and draw it. No letters or numbers!',
      'Everyone else types guesses into the chat. Fast guesses earn more points.',
      'Letters are revealed as a hint when the clock runs down.',
      'Everyone draws once per round. Most points after the last round wins.',
    ],
    options: [
      { key: 'rounds', label: 'Rounds', choices: [1, 2, 3, 4, 5], default: 3 },
      { key: 'time', label: 'Draw time', choices: [{ value: 30, label: '30 sec' }, { value: 45, label: '45 sec' }, { value: 60, label: '60 sec' }, { value: 80, label: '80 sec' }, { value: 100, label: '100 sec' }], default: 60 },
      { key: 'hints', label: 'Letter hints', choices: [{ value: 'on', label: 'On' }, { value: 'off', label: 'Off' }], default: 'on' },
    ],
    load: () => import('./sketch.js'),
  },
  {
    id: 'beans',
    name: 'Bean Trader',
    emoji: '🫘',
    color: '#2f9e44',
    cat: 'Cards',
    tags: ['Trading', 'Negotiation'],
    min: 2,
    max: 7,
    tagline: 'Plant, trade and harvest beans.',
    desc: 'A wheeling-and-dealing card game about farming beans. You can never rearrange your hand, so you need your friends — trade, donate and haggle to plant big, valuable fields and harvest the most coins.',
    howto: [
      'Each turn, plant the first card of your hand in a field. A field only holds one kind of bean. You may plant the next card too.',
      'Then two cards are turned face-up. Trade or give them (and any cards from your hands) to other players — every trade involves the player whose turn it is. Anyone can propose offers, and you accept or decline.',
      'Every bean you receive or keep must be planted right away. No room? Harvest a field first.',
      'Harvest to turn beans into coins using the price chart (📖 Prices): bigger fields of rarer beans pay more. Leftover beans are discarded.',
      'Finally draw 3 cards to the BACK of your hand. With 4+ players you can buy a third field for 3 coins.',
      'The game ends when the draw pile has run out for the third time. Most coins wins!',
    ],
    load: () => import('./beans.js'),
  },
  {
    id: 'pool',
    name: '8-Ball Pool',
    emoji: '🎱',
    color: '#0f8a5a',
    cat: 'Arcade',
    tags: ['Physics', 'Teams'],
    min: 2,
    max: 4,
    tagline: 'Rack ’em up. Call your shots.',
    desc: 'Classic 8-ball on a full-size table with real ball physics. Two players go head-to-head — or play 2 vs 2 with partners taking turns.',
    howto: [
      'Drag on the table to aim (the dotted line shows where the cue ball goes). Set the power with the slider, then press Shoot (or Space).',
      'After you sink your first ball, you own solids (1–7) or stripes (9–15). Keep shooting while you pot your own balls.',
      'Scratching, missing everything or hitting the wrong ball first is a foul — your opponent gets ball-in-hand: drag the cue ball anywhere.',
      'Clear all your balls, then sink the 8-ball to win. Sink it early and you lose!',
    ],
    load: () => import('./pool.js'),
  },
  {
    id: 'colorrush',
    name: 'Color Rush',
    emoji: '🌈',
    color: '#e5383b',
    cat: 'Cards',
    tags: ['Classic', 'Fast'],
    min: 2,
    max: 8,
    tagline: 'Match colors, block friends, be first out.',
    desc: 'The classic match-the-color shedding card game. Dump your hand before anyone else — use Block, Flip, +2 and Wild cards to wreck your friends’ plans. Don’t forget to shout UNO!',
    howto: [
      'Play a card that matches the top card’s color or number/symbol. Wild cards (🌈, +4) go on anything and let you pick the color.',
      '🚫 skips the next player, 🔁 reverses direction, +2 / +4 make the next player draw and lose their turn.',
      'Can’t play? Tap the DRAW pile. If the card you drew fits, you may play it right away.',
      'When you are down to your last card, hit the 🔔 UNO! button — if someone taps “Catch!” before you do, you draw 2.',
      'First to empty their hand wins the round. Play single rounds or race to 100 / 200 points.',
    ],
    options: [{ key: 'target', label: 'Game length', choices: [{ value: 0, label: 'Single round' }, { value: 100, label: 'First to 100 pts' }, { value: 200, label: 'First to 200 pts' }], default: 0 }],
    load: () => import('./colorrush.js'),
  },
  {
    id: 'poker',
    name: 'Texas Hold’em',
    emoji: '🃏',
    color: '#1e8449',
    cat: 'Cards',
    tags: ['Poker', 'Bluffing'],
    min: 2,
    max: 8,
    tagline: 'No-limit poker with your friends.',
    desc: 'Everyone starts with the same pile of chips. Two hole cards, five community cards, four betting rounds — bluff, bet, and take your friends’ chips. Full side-pot rules and action timers included.',
    howto: [
      'Each player gets two private cards; five shared cards are dealt in three stages (flop, turn, river).',
      'On your turn: Fold, Check/Call, or Bet/Raise (use the slider or the quick buttons, or go all-in).',
      'Best five-card hand wins the pot: straight flush > four of a kind > full house > flush > straight > three of a kind > two pair > pair > high card.',
      'You have 40 seconds per action or you auto-fold. The game ends when one player has all the chips (or after the hand limit).',
    ],
    options: [
      { key: 'chips', label: 'Starting chips', choices: [500, 1000, 2000], default: 1000 },
      { key: 'hands', label: 'Length', choices: [{ value: 0, label: 'Until one player is left' }, { value: 10, label: '10 hands' }, { value: 20, label: '20 hands' }, { value: 40, label: '40 hands' }], default: 0 },
      { key: 'blinds', label: 'Blinds', choices: [{ value: 'fixed', label: 'Fixed' }, { value: 'rising', label: 'Double every 5 hands' }], default: 'rising' },
    ],
    load: () => import('./poker.js'),
  },
  {
    id: 'chess',
    name: 'Chess',
    emoji: '♟️',
    color: '#8d6e63',
    cat: 'Board',
    tags: ['Classic', 'Strategy'],
    min: 2,
    max: 2,
    tagline: 'The royal game, head to head.',
    desc: 'Full chess rules — castling, en passant, promotion, check and checkmate — with optional clocks, draw offers and resignation. Colors are assigned at random.',
    howto: [
      'Click one of your pieces to see its legal moves, then click a highlighted square to move.',
      'Pawns that reach the far side can promote — pick the new piece from the popup.',
      'Win by checkmate, or when your opponent resigns or runs out of time. Stalemate, repetition and insufficient material are draws.',
    ],
    options: [{ key: 'time', label: 'Clock', choices: [{ value: 0, label: 'No clock' }, { value: 3, label: '3 min + 2s' }, { value: 5, label: '5 min + 2s' }, { value: 10, label: '10 min + 2s' }], default: 0 }],
    load: () => import('./chess.js'),
  },
  {
    id: 'liars',
    name: 'Liar’s Dice',
    emoji: '🎲',
    color: '#c0392b',
    cat: 'Bluffing',
    tags: ['Bluffing', 'Dice'],
    min: 2,
    max: 6,
    tagline: 'Bid big. Spot the bluff.',
    desc: 'Everyone secretly rolls their dice under a cup. Take turns bidding how many dice of a number are on the whole table — or call the last bidder a liar. Lose a challenge, lose a die. Last player with dice wins.',
    howto: [
      'Look at your own dice. Then bid a quantity and a face, e.g. “six 4s” — you’re claiming that many 4s exist among everyone’s dice combined.',
      'Each bid must beat the previous: a higher quantity, or the same quantity with a higher face. (Wild 1s have their own conversion rules: halve the quantity going to 1s, double + 1 coming back.)',
      'Or call “Liar!” — all cups are lifted. If the bid was right, the caller loses a die; if it was a bluff, the bidder does.',
      '1s count as wild for every face except bids on 1s themselves (can be switched off in the lobby).',
    ],
    options: [
      { key: 'dice', label: 'Starting dice', choices: [3, 4, 5, 6], default: 5 },
      { key: 'wild', label: 'Wild ones', choices: [{ value: 'on', label: 'On' }, { value: 'off', label: 'Off' }], default: 'on' },
    ],
    load: () => import('./liars.js'),
  },
  {
    id: 'bomber',
    name: 'Bomber Arena',
    emoji: '💣',
    color: '#e67e22',
    cat: 'Arcade',
    tags: ['Retro', 'Action'],
    min: 2,
    max: 4,
    tagline: 'Blast your friends. Dodge the flames.',
    desc: 'A classic 8-bit-style bomb-dropping maze battle. Blow up crates, grab power-ups and trap your friends. Last one standing wins the round — and the arena closes in if you take too long.',
    howto: [
      'Move with the arrow keys or WASD (on phones: the on-screen pad). Drop a bomb with Space (or the 💣 button).',
      'Bombs explode after about 2 seconds in a cross shape, and chain-react with other bombs. Crates (brown) can be blown up; walls (gray) can’t.',
      'Crates sometimes drop power-ups: 💣 more bombs, 🔥 bigger blasts, 👟 faster movement.',
      'Don’t get caught in a blast — including your own! Last player alive wins the round. After 75 seconds the walls start closing in.',
    ],
    options: [{ key: 'wins', label: 'Rounds to win', choices: [1, 2, 3, 5], default: 2 }],
    load: () => import('./bomber.js'),
  },
  {
    id: 'tanks',
    name: 'Tank Battle',
    emoji: '🪖',
    color: '#6b8e23',
    cat: 'Arcade',
    tags: ['Retro', 'Shooter'],
    min: 2,
    max: 4,
    tagline: 'Retro tank arena, last tank rolling.',
    desc: 'Drive your tank around a randomly generated fortress, blast through brick walls and hunt your friends. Respawn and go again — first to the kill target wins.',
    howto: [
      'Move with the arrow keys or WASD, fire with Space (on phones: the pad and 🔥 button).',
      'Red brick walls can be shot away; steel walls can’t. Bullets cancel each other out.',
      'You can have two shots in the air at once. After a kill you respawn with a short shield.',
      'First player to reach the kill target wins.',
    ],
    options: [{ key: 'kills', label: 'Kills to win', choices: [5, 10, 15, 20], default: 10 }],
    load: () => import('./tanks.js'),
  },
  {
    id: 'snake',
    name: 'Snake Arena',
    emoji: '🐍',
    color: '#2ecc71',
    cat: 'Arcade',
    tags: ['Retro', 'Fast'],
    min: 2,
    max: 8,
    tagline: 'Slither, grow, outlast.',
    desc: 'Everyone’s snake slithers around the same board. Eat apples to grow longer — but don’t hit a wall or another snake. Crashed snakes turn into snacks for the survivors!',
    howto: [
      'Steer with the arrow keys / WASD, the on-screen pad, or by swiping on the board.',
      'Eat 🍎 to grow. Crashed snakes drop 🍏 for others to eat.',
      'Hitting a wall, your own tail or any other snake knocks you out. Head-on crashes knock out both snakes.',
      'Last snake slithering wins the round. First to the target number of round wins takes the game.',
    ],
    options: [
      { key: 'speed', label: 'Speed', choices: [{ value: 'slow', label: 'Chill' }, { value: 'normal', label: 'Normal' }, { value: 'fast', label: 'Frantic' }], default: 'normal' },
      { key: 'wins', label: 'Rounds to win', choices: [1, 2, 3, 5], default: 2 },
    ],
    load: () => import('./snake.js'),
  },
  {
    id: 'blocks',
    name: 'Block Battle',
    emoji: '🧱',
    color: '#8e44ad',
    cat: 'Arcade',
    tags: ['Retro', 'Versus', 'Puzzle'],
    min: 2,
    max: 6,
    tagline: 'Falling blocks — and they fall on your friends.',
    desc: 'Everybody stacks falling blocks on their own board at the same time. Clear lines to send garbage rows to your opponents — and survive to be the last board standing.',
    howto: [
      '← → move, ↑ (or X) rotate, Z rotate back, ↓ soft drop, Space hard drop, C hold a piece. On phones use the on-screen buttons.',
      'Fill a whole row to clear it. Clearing 2+ rows at once (or chaining combos) sends garbage rows to a random opponent.',
      'The red bar beside your board shows incoming garbage — clear lines before it lands to cancel it out.',
      'If your stack reaches the top, you’re out. Last board standing wins!',
    ],
    load: () => import('./blocks.js'),
  },
  {
    id: 'sumo',
    name: 'Sumo Brawl',
    emoji: '🥋',
    color: '#d35400',
    cat: 'Party',
    tags: ['Chaos', 'Physics'],
    min: 2,
    max: 8,
    tagline: 'Shove your friends into the lava.',
    desc: 'Everyone crowds onto a floating platform that keeps shrinking. Bump, dash and shove your friends off the edge — last one standing wins the round.',
    howto: [
      'Move with arrow keys / WASD, or press and hold on the arena and your fighter walks toward your finger.',
      'Press Space (or the 💨 button) to dash — it gives a big shove, then needs a moment to recharge.',
      'After 10 seconds the platform starts to shrink. Fall off and you’re out!',
      'Win the most rounds to be crowned sumo champion.',
    ],
    options: [{ key: 'wins', label: 'Rounds to win', choices: [1, 2, 3, 5], default: 3 }],
    load: () => import('./sumo.js'),
  },
  {
    id: 'pong',
    name: 'Pong Arena',
    emoji: '🏓',
    color: '#00b4d8',
    cat: 'Retro',
    tags: ['Classic', 'Reflexes'],
    min: 2,
    max: 4,
    tagline: 'Retro paddle battle for up to 4.',
    desc: 'Old-school Pong turned up a notch: a square arena with one paddle per player. Don’t let the ball slip past — lose all your lives and your side becomes a wall.',
    howto: [
      'Slide your paddle with the arrow keys (or A/D, W/S) — or just drag your finger/mouse along your side.',
      'Hit the ball off the edge of your paddle to steer it. The ball speeds up with every hit!',
      'Each time the ball gets past you, you lose a life. At 0 lives your side turns into a wall.',
      'Last player with lives left wins.',
    ],
    options: [{ key: 'lives', label: 'Lives', choices: [3, 5, 7, 10], default: 5 }],
    load: () => import('./pong.js'),
  },
  {
    id: 'typeracer',
    name: 'Type Racer',
    emoji: '⌨️',
    color: '#0984e3',
    cat: 'Words',
    tags: ['Typing', 'Speed'],
    min: 2,
    max: 8,
    tagline: 'Race your friends on the keyboard.',
    desc: 'Everyone gets the same passage. Type it perfectly and faster than your friends — watch your avatars race along the track. Points for every finishing place.',
    howto: [
      'When the countdown ends, type the passage in the box. Mistakes show in red — fix them to keep going.',
      'Your avatar moves along the track as you type correctly. First across the line gets the most points.',
      'After the first finisher, everyone else has 30 seconds to finish.',
      'Most points after all rounds wins (average speed breaks ties).',
    ],
    options: [{ key: 'rounds', label: 'Rounds', choices: [1, 2, 3, 5], default: 3 }],
    load: () => import('./typeracer.js'),
  },
  {
    id: 'imposter',
    name: 'Imposter',
    emoji: '🕵️',
    color: '#c0392b',
    cat: 'Bluffing',
    tags: ['Bluffing', 'Words', 'Social'],
    min: 3,
    max: 10,
    tagline: 'One of you doesn’t know the word.',
    desc: 'Everyone gets the same secret word — except the imposter, who only knows the category. Give one-word clues that prove you know it without giving it away, then vote out the faker.',
    howto: [
      'Tap your card to peek at your secret word (tap again to hide it). The imposter only sees the category.',
      'Take turns giving a one-word clue. Be vague enough that the imposter can’t guess the word — but specific enough that your friends trust you.',
      'Discuss in the chat (or out loud), then everyone votes for who they think the imposter is.',
      'If the imposter is caught, they get one guess at the secret word to steal the win. Imposters score 3 points for escaping; the crew scores 1 (+1 for voting right).',
    ],
    options: [
      { key: 'rounds', label: 'Rounds', choices: [3, 5, 7], default: 3 },
      { key: 'clues', label: 'Clue rounds', choices: [1, 2], default: 1 },
      { key: 'imposters', label: 'Imposters (7+ players)', choices: [{ value: '1', label: 'One' }, { value: '2', label: 'Two' }], default: '1' },
      { key: 'hint', label: 'Imposter sees category', choices: [{ value: 'on', label: 'Yes' }, { value: 'off', label: 'No (hard mode)' }], default: 'on' },
    ],
    load: () => import('./imposter.js'),
  },
  {
    id: 'wordspies',
    name: 'Word Spies',
    emoji: '🔤',
    color: '#34495e',
    cat: 'Words',
    tags: ['Teams', 'Words', 'Codenames-style'],
    min: 4,
    max: 10,
    tagline: 'Two teams. One-word clues. Don’t touch the assassin.',
    desc: 'Two teams of secret agents race to find their spies on a 5×5 board of words. Each team’s spymaster gives one-word clues; operatives guess. Pick the assassin and you lose instantly!',
    howto: [
      'Players are split into a Red and a Blue team. Each team has a spymaster who can see the secret key.',
      'The spymaster gives a one-word clue and a number — how many cards relate to it. (The clue can’t be a word on the board.)',
      'Operatives tap a card to select it and tap again to flip it. Your team’s color: keep going (up to number + 1 guesses). Neutral or enemy: your turn ends.',
      'Find all your team’s agents first to win. Flip the assassin and your team loses!',
    ],
    load: () => import('./wordspies.js'),
  },
  {
    id: 'movie',
    name: 'Movie Night',
    emoji: '🍿',
    color: '#8e44ad',
    cat: 'Hangout',
    tags: ['Screen share', 'Voice & video'],
    min: 2,
    max: 12,
    tagline: 'Share your screen and watch together.',
    desc: 'Like Discord screen sharing: one person shares a screen, window or browser tab — with or without its sound — and everyone else watches live. Talk and show your face with the built-in voice & video call, and fire off emoji reactions.',
    howto: [
      'Press “Share my screen”, choose a tab, window or whole screen. Tick “Share sound” (and, in Chrome, “Also share tab audio” in the picker) if you want everyone to hear it.',
      'Pick a quality: smooth movie, HD, 60 fps gaming, or sharp slides & text. With many viewers the quality is automatically capped so the stream stays smooth.',
      'Use the 🎤 and 📹 buttons at the top to join the voice/video call any time — tap a face to enlarge it. Headphones avoid echo.',
      'Anyone can present when nobody else is; the host can stop a share. Phones can watch and chat but can’t share their screen.',
    ],
    load: () => import('./movie.js'),
  },
  {
    id: 'retro',
    name: 'Retro Console',
    emoji: '🕹️',
    color: '#c0392b',
    cat: 'Retro',
    tags: ['NES', 'Emulator', 'Bring your own ROM'],
    min: 1,
    max: 8,
    tagline: 'Play real NES games together, remotely.',
    desc: 'The host’s browser runs a NES emulator and streams the picture and sound to everyone in the room; the first two players get controllers 1 and 2, the rest can watch. Includes free homebrew games — or load your own legally-owned .nes file.',
    howto: [
      'The host picks a game: a built-in free homebrew cartridge, or a .nes ROM from their own computer (it never gets uploaded anywhere).',
      'Player 1 = the first player in the room, Player 2 = the second. Everyone else watches the stream.',
      'Keyboard: arrow keys = D-pad, X = A, Z = B, Enter = Start, C or Shift = Select. On phones use the on-screen pad. USB/Bluetooth gamepads work too.',
      'The host must keep their tab open and visible — it runs the game for everyone. Expect about a tenth of a second of lag for guests.',
      'Only play games you own. This project is not affiliated with Nintendo.',
    ],
    load: () => import('./retro.js'),
  },
  {
    id: 'telephone',
    name: 'Doodle Telephone',
    emoji: '📞',
    color: '#e5399b',
    cat: 'Drawing',
    tags: ['Drawing', 'Hilarious', 'No losers'],
    min: 3,
    max: 12,
    tagline: 'Write, draw, describe — and watch it go wrong.',
    desc: 'Everybody starts a story with a silly sentence. Then the stories rotate: you draw what you read, the next person describes your drawing, and so on. The final reveal turns everyone’s misunderstandings into one big joke.',
    help: {
      goal: 'There are no winners — just laugh at how far each story drifts. Tap ♥ on your favourite steps; the most-loved author gets the crown.',
      steps: [
        'Step 1: everyone writes a funny sentence (or taps “Surprise me”).',
        'Each step you get another player’s story: if it’s a sentence, DRAW it; if it’s a drawing, describe it in one sentence.',
        'Finish before the timer ends — whatever you have is sent automatically.',
        'When every story has gone around, the host steps through each one. Heart the best bits!',
      ],
      tips: ['Draw fast and simple — you only get one minute.', 'Describe what you see, not what you think it should be.'],
    },
    options: [
      { key: 'steps', label: 'Story length', choices: [{ value: 'full', label: 'Full (everyone plays every story)' }, { value: 'short', label: 'Short (4 steps)' }], default: 'full' },
      { key: 'drawTime', label: 'Drawing time', choices: [{ value: 40, label: '40 sec' }, { value: 60, label: '60 sec' }, { value: 90, label: '90 sec' }], default: 60 },
    ],
    load: () => import('./telephone.js'),
  },
  {
    id: 'captions', name: 'Caption Clash', emoji: '🤣', color: '#f57c00', cat: 'Party', tags: ['Captions', 'Voting'], min: 3, max: 10,
    tagline: 'Caption the picture. Win the room.',
    desc: 'Every round shows a ridiculous picture. Everybody writes a top and bottom caption, then the room votes — anonymously — for the funniest. Your friends’ inside jokes make it ten times better.',
    help: { steps: ['A picture appears. Write a top and bottom caption (either can be empty).', 'Submit before the timer runs out.', 'Then all captions are shown — tap the funniest. You can’t vote for your own.', 'Each vote is worth 100 points, and the winning caption gets a 100 bonus.'], tips: ['Short and punchy beats long and clever.', 'Inside jokes win rooms.'] },
    options: [{ key: 'rounds', label: 'Rounds', choices: [3, 5, 7], default: 3 }],
    load: () => import('./captions.js'),
  },
  {
    id: 'quipclash', name: 'Quip Clash', emoji: '💬', color: '#e5399b', cat: 'Party', tags: ['Writing', 'Head-to-head'], min: 3, max: 8,
    tagline: 'Be funnier than your friends.',
    desc: 'Everyone gets two silly prompts. Each prompt is answered by two players, and everyone else votes on whose answer is funnier. Win the vote — or get everyone to agree for a QUIPCLASH bonus.',
    help: { steps: ['You get two prompts. Type your funniest answer to each (70 characters max).', 'Then each prompt becomes a duel: two answers appear anonymously and the rest of the room votes.', 'You can’t vote in duels you’re part of.', '100 points per vote. If everyone picks you: +100 bonus!'], tips: ['Be specific — vague answers are never funny.'] },
    options: [{ key: 'rounds', label: 'Rounds', choices: [1, 2, 3], default: 2 }],
    load: () => import('./quipclash.js'),
  },
  {
    id: 'fibquiz', name: 'Fib Quiz', emoji: '🤥', color: '#8e4de8', cat: 'Bluffing', tags: ['Trivia', 'Bluffing'], min: 2, max: 10,
    tagline: 'Fool your friends with fake facts.',
    desc: 'You get a strange but true fact with the answer missing. Everyone invents a believable fake answer — then everyone tries to pick the real one out of the pile of fibs.',
    help: { steps: ['A fact appears with a blank. Write a believable fake answer that fits.', 'All the fakes plus the real answer are shuffled together.', 'Pick the one you think is TRUE. (You can’t pick your own fib.)', '+500 for finding the truth, +250 for every friend who falls for your fib.'], tips: ['Match the style of the question — if it’s a number, give a number.', 'Funny fibs are fun but believable fibs score.'] },
    options: [{ key: 'rounds', label: 'Questions', choices: [4, 6, 8, 10], default: 6 }],
    load: () => import('./fibquiz.js'),
  },
  {
    id: 'triviatrap', name: 'Trivia Trap', emoji: '🪤', color: '#ea4335', cat: 'Party', tags: ['Trivia', 'Survival'], min: 2, max: 10,
    tagline: 'Trivia where wrong answers cost hearts.',
    desc: 'Quick-fire trivia with hearts on the line. Answer fast for bonus points — answer wrong and you lose a heart. Every few questions you must pick a trap door, and one of them is rigged. Last player standing wins.',
    help: { steps: ['Read the question and tap your answer within 15 seconds.', 'Right: 100 points plus up to 100 speed bonus. Wrong or too slow: you lose a heart.', 'Every 4th round is a trap door round: pick a door 1–3. Whoever picks the trapped door loses a heart.', 'Out of hearts and you’re out. Survivors with the most points win.'] },
    options: [{ key: 'questions', label: 'Questions', choices: [8, 12, 16, 20], default: 12 }, { key: 'lives', label: 'Hearts', choices: [2, 3, 4], default: 3 }],
    load: () => import('./triviatrap.js'),
  },
  {
    id: 'letterdash', name: 'Letter Dash', emoji: '🔤', color: '#0fa9c2', cat: 'Words', tags: ['Categories', 'Speed'], min: 2, max: 10,
    tagline: 'One letter. Six categories. Go!',
    desc: 'A letter and six categories — write an answer that starts with that letter for each one before time runs out. Unique answers score big; if your friend wrote the same thing you share fewer points.',
    help: { steps: ['You get a letter and six categories. Fill in an answer for each that starts with the letter.', 'Press Done (or wait for the timer).', 'Review everyone’s answers and flag any that don’t fit the category.', 'Unique answers score 10; duplicates score 5; flagged or wrong-letter answers score 0.'], tips: ['Think of the weird answers — nobody else will write them.'] },
    options: [{ key: 'rounds', label: 'Rounds', choices: [2, 3, 5], default: 3 }],
    load: () => import('./letterdash.js'),
  },
  {
    id: 'rowrumble', name: 'Row Rumble', emoji: '🐂', color: '#ea4335', cat: 'Cards', tags: ['Simultaneous', 'Take-that'], min: 2, max: 10,
    tagline: 'Pick a card. Don’t take the 6th!',
    desc: 'Everyone secretly picks a card and all are revealed at once. Cards are placed in ascending order onto four rows — and whoever places the sixth card in a row has to take the whole row, bull heads and all. Lowest total wins.',
    help: { goal: 'Finish with the FEWEST bull heads (🐂). Cards with more heads cost more when you take them.', steps: ['Everyone holds 10 cards numbered 1–104. Four rows each start with one card.', 'Each turn everyone secretly picks one card; all are revealed together.', 'Starting with the lowest card, each goes onto the row whose last card is the closest lower number.', 'If a row already has 5 cards, you take those 5 (their 🐂) and your card starts a new row.', 'If your card is lower than every row end, you pick any row to take.', 'Play 10 turns per round; the game ends when someone reaches 66 🐂 (or after one round in short mode).'], tips: ['Low cards are risky early; high cards risky late.', 'Watch how full each row is.'] },
    options: [{ key: 'length', label: 'Game length', choices: [{ value: 'full', label: 'Until 66 bulls' }, { value: 'short', label: 'One round' }], default: 'full' }],
    load: () => import('./rowrumble.js'),
  },
  {
    id: 'dialitin', name: 'Dial It In', emoji: '🎯', color: '#0fa9c2', cat: 'Party', tags: ['Clues', 'Co-op-ish'], min: 3, max: 10,
    tagline: 'Get on the same wavelength.',
    desc: 'One player is the psychic: they see a secret spot on a spectrum like “Cold ↔ Hot” and give a clue. Everyone else slides the dial to where they think it is. The closer you are, the more points you earn!',
    help: { steps: ['The psychic sees the target zone on the dial and types a clue (no numbers or direct hints!).', 'Everyone else drags the slider to where they think the target is and locks it in.', 'Reveal: bullseye +4, close +3, nearby +2.', 'The psychic earns the average of everyone’s points. Everybody takes a turn as psychic.'], tips: ['Debate the clue out loud — is a microwave “extraordinary”?', 'Clue about the spot on the line, not just the ends.'] },
    options: [{ key: 'laps', label: 'Laps (rounds per player)', choices: [1, 2], default: 1 }],
    load: () => import('./dialitin.js'),
  },
  {
    id: 'petals', name: 'Petals & Thorns', emoji: '🌹', color: '#c2185b', cat: 'Bluffing', tags: ['Bluffing', 'Bidding'], min: 3, max: 6,
    tagline: 'Bid big, bluff bigger, avoid the thorns.',
    desc: 'Each player has three petals and one thorn. Secretly stack discs face-down, then bid on how many you can flip over without finding a thorn. Win two challenges to win — fail and you lose a disc!',
    help: { goal: 'Be the first to win 2 challenges, or be the last player with discs.', steps: ['Everyone secretly places one disc face-down (a petal ✿ or the thorn ☠).', 'In turn, add another disc to your stack — or start the bidding by claiming how many discs you can flip.', 'Others raise the bid or pass. The highest bidder becomes the challenger.', 'The challenger must flip that many discs — their own first, then any rivals’ stacks (top disc first).', 'Find only petals: you win a point! Hit a thorn: you lose a random disc (or your choice if it was your own).'], tips: ['Putting your thorn on the bottom of a big stack makes you look safe.', 'A tiny bid with a thorn on top is a classic bluff.'] },
    options: [{ key: 'points', label: 'Points to win', choices: [1, 2, 3], default: 2 }],
    load: () => import('./petals.js'),
  },
  {
    id: 'uniqueclues', name: 'Unique Clues', emoji: '💡', color: '#fbbc04', cat: 'Words', tags: ['Co-op', 'Clues'], min: 3, max: 8,
    tagline: 'Great minds think alike… and cancel out.',
    desc: 'A cooperative word game: everyone except the guesser sees a secret word and writes ONE clue. Clues that match are deleted before the guesser sees them — so the best clues are the unique ones. Score as many correct guesses as you can together.',
    help: { goal: 'Work together to guess as many secret words as possible across all cards.', steps: ['One player is the guesser and looks away. Everyone else sees the secret word.', 'Each other player writes a single-word clue.', 'Duplicate clues (and illegal ones that contain the word) are removed. You can flag suspicious clues.', 'The guesser sees what’s left and guesses — or passes.', 'Right: +1. Wrong: the card is lost.'], tips: ['Don’t pick the most obvious clue — someone else will!', 'Don’t say anything out loud during the clue phase.'] },
    options: [{ key: 'cards', label: 'Cards', choices: [5, 8, 13], default: 8 }],
    load: () => import('./uniqueclues.js'),
  },
  {
    id: 'wordbomb', name: 'Word Bomb', emoji: '💣', color: '#f57c00', cat: 'Words', tags: ['Typing', 'Frantic'], min: 2, max: 8,
    tagline: 'Type a word before the bomb explodes.',
    desc: 'A bomb with a hidden fuse gets passed around. When it’s yours, type any real word that contains the letters shown — fast! Words can’t be reused, and when the bomb goes off, whoever holds it loses a heart.',
    help: { steps: ['When the bomb is in your hands, type a word that contains the highlighted letters (anywhere in the word).', 'Press Send/Enter. Valid word: the bomb passes to the next player with new letters.', 'Invalid, repeated or missing letters: try again quickly!', 'If the bomb explodes in your hands, you lose a heart. Last player standing wins.'], tips: ['Everyone can see what you’re typing…', 'Short words are fine — speed beats cleverness.'] },
    options: [{ key: 'lives', label: 'Hearts', choices: [2, 3, 4], default: 2 }, { key: 'level', label: 'Difficulty', choices: [{ value: 'easy', label: 'Easy letters' }, { value: 'normal', label: 'Normal' }, { value: 'hard', label: 'Hard letters' }], default: 'normal' }],
    load: () => import('./wordbomb.js'),
  },
  {
    id: 'drawbattle', name: 'Doodle Duel', emoji: '⚔️', color: '#5e35b1', cat: 'Drawing', tags: ['Teams', 'Drawing'], min: 4, max: 12,
    tagline: 'Blue vs Red — draw fast, guess faster.',
    desc: 'Two teams battle it out in a drawing showdown. Teams take turns sending a drawer to the canvas — but everybody can guess, so the other team can steal the points with a quicker guess. Team with the most points wins.',
    help: { goal: 'Score more points for your team than the other team.', steps: ['Players are split into Blue and Red (you’ll see a coloured dot by each name).', 'Teams alternate sending a drawer. The drawer picks one of three words and draws it — no letters or numbers.', 'EVERYONE (both teams) can guess in the chat box. The faster the correct guess, the more points go to the guesser’s team.', 'The drawer’s team also earns points when someone guesses.', 'After all rounds, the team total decides the winner.'], tips: ['Draw big and simple.', 'Watch the other team’s drawer — a lucky steal is worth as much!'] },
    options: [{ key: 'teams', label: 'Mode', choices: [{ value: 'on', label: 'Team battle' }], default: 'on' }, { key: 'rounds', label: 'Rounds', choices: [1, 2, 3, 4], default: 2 }, { key: 'time', label: 'Draw time', choices: [{ value: 45, label: '45 sec' }, { value: 60, label: '60 sec' }, { value: 80, label: '80 sec' }], default: 60 }, { key: 'hints', label: 'Letter hints', choices: [{ value: 'on', label: 'On' }, { value: 'off', label: 'Off' }], default: 'on' }],
    load: () => import('./sketch.js'),
  },
  {
    id: 'spyplace', name: 'Who’s the Spy?', emoji: '🕵️', color: '#00897b', cat: 'Bluffing', tags: ['Deduction', 'Conversation'], min: 4, max: 10,
    tagline: 'Everyone knows where you are — except the spy.',
    desc: 'Everyone except one player is shown the same secret location. Take turns asking each other questions — vague enough to protect the place, specific enough to expose the spy. The spy has to bluff along and work out where you are.',
    help: { goal: 'Crew: unmask the spy. Spy: stay hidden or figure out the location.', steps: ['Everyone but the spy sees the secret location. The spy only knows they’re the spy.', 'A random player starts by asking another player any question (out loud, or in chat). That player answers, then asks someone else.', 'You can’t ask the player who just asked you.', 'Any player may accuse once per round: all others vote — it must be unanimous to stick.', 'The spy can reveal themselves any time to guess the location. Run out the clock and everyone votes.'], tips: ['Answer in a way that fits the place — but isn’t a giveaway.', 'Spies: listen for words that hint at the location.'] },
    options: [{ key: 'rounds', label: 'Rounds', choices: [2, 3, 5], default: 3 }, { key: 'time', label: 'Round timer', choices: [{ value: 4, label: '4 min' }, { value: 6, label: '6 min' }, { value: 8, label: '8 min' }], default: 6 }],
    load: () => import('./spyplace.js'),
  },
  {
    id: 'codecrack', name: 'Code Crackers', emoji: '🔐', color: '#1565c0', cat: 'Words', tags: ['Teams', 'Deduction'], min: 4, max: 8,
    tagline: 'Send secret messages. Intercept theirs.',
    desc: 'Each team has four secret words, numbered 1–4. Every turn one player gets a secret 3-digit code and gives three clues, one per digit, so teammates can decode it — without letting the other team work out your system.',
    help: { goal: 'Be the first to intercept the other team’s code twice — and avoid miscommunicating twice yourself.', steps: ['You can see only YOUR team’s four secret words (numbered 1–4).', 'The encryptor gets a secret code like 3-1-4 and writes one clue per digit that points to that numbered word.', 'Teammates guess the code. From round 2 the other team also tries to intercept the code.', 'Wrong team guess = black token (miscommunication). Correct interception = white token for the interceptors.', 'The clue history for each number is visible to everyone — study the other team’s clues!'], tips: ['Vary your clue style so your history doesn’t give it away.', 'Spying on old clues is how you intercept.'] },
    load: () => import('./codecrack.js'),
  },
  {
    id: 'shadowquest', name: 'Shadow Quest', emoji: '🗡️', color: '#4527a0', cat: 'Bluffing', tags: ['Hidden roles', 'Deduction'], min: 5, max: 10,
    tagline: 'Heroes vs. hidden Shadows. Who can you trust?',
    desc: 'A secret-role quest game. Heroes try to complete three quests; Shadows hide among them and sabotage. Merlin knows who the Shadows are — but if the heroes win, the Assassin gets one shot at naming Merlin.',
    help: { goal: 'Heroes: complete 3 quests. Shadows: fail 3 quests (or find Merlin).', steps: ['Tap your role card to see who you are (tap again to hide it). Shadows see each other; Merlin sees the Shadows.', 'The leader proposes a team for the quest; everyone votes to approve or reject it. Five rejected teams in a row and the Shadows win.', 'Approved team members secretly play Success or Fail. Heroes must play Success; Shadows may sabotage.', 'One Fail sinks a quest (quest 4 with 7+ players needs two).', 'If three quests succeed, the Assassin names who they think Merlin is. A correct guess steals the win for the Shadows.'], tips: ['Merlin: help the team, but don’t be too obvious.', 'Shadows: sometimes play Success to blend in.'] },
    load: () => import('./shadowquest.js'),
  },
  {
    id: 'royalletters', name: 'Royal Letters', emoji: '💌', color: '#c2185b', cat: 'Cards', tags: ['Deduction', 'Quick'], min: 2, max: 4,
    tagline: 'One card in hand. Send your love letter to the princess.',
    desc: 'A tiny deck with big drama. Each turn you draw a card and play one, using its power to peek, swap or knock out rivals. Hold the highest card at the end of the round (or be the last one standing) to win a token of affection.',
    help: { goal: 'Be first to collect enough tokens of affection (7 for 2 players, 5 for 3, 4 for 4).', steps: ['You always hold one card; on your turn you draw a second and play one of the two.', 'Each card has a power: 1 Guard guesses a card, 2 Priest peeks, 3 Baron compares, 4 Handmaid protects, 5 Prince forces a discard, 6 King swaps hands, 7 Countess must be played with King/Prince, 8 Princess loses if discarded.', 'Tap a card to play it, then tap the player you want to target.', 'The round ends when the deck runs out or one player remains. Highest card wins the round.'], tips: ['Track every discarded card — it narrows down what others can hold.', 'Keep the Princess safe and bluff with the Countess.'] },
    options: [{ key: 'length', label: 'Game length', choices: [{ value: 'normal', label: 'Normal' }, { value: 'short', label: 'Short (2 tokens)' }], default: 'normal' }],
    load: () => import('./royalletters.js'),
  },
  {
    id: 'tunneltraitors', name: 'Tunnel Traitors', emoji: '⛏️', color: '#ef6c00', cat: 'Bluffing', tags: ['Hidden roles', 'Tile laying'], min: 3, max: 10,
    tagline: 'Dig for gold — but not everyone is on your side.',
    desc: 'A mining game of secret saboteurs. Lay tunnel cards to reach the hidden gold, while saboteurs break tools, drop dead ends and cause rockfalls. Three rounds, new secret roles each round — most gold wins.',
    help: { goal: 'Diggers: reach the gold before the cards run out. Saboteurs: stop them.', steps: ['Each round you secretly get a role: Gold Digger or Saboteur. Tap the role banner to peek at it any time.', 'On your turn, play one card (then draw one): a tunnel card, an action card, or discard a card.', 'Tunnel cards must connect to the start through matching openings. Tap a card, then tap a green spot. Use ⟳ to rotate it.', 'Break a player’s pickaxe, lamp or cart to stop them digging; Repair cards fix them. Rockfall removes a tunnel; Map lets you secretly peek at one of the three goal cards.', 'If the tunnel reaches the gold, diggers win and share the gold. If the cards run out first, saboteurs win.'], tips: ['Saboteurs don’t know each other — and diggers can’t be sure of anyone.', 'Dead ends look innocent… or do they?'] },
    options: [{ key: 'rounds', label: 'Rounds', choices: [1, 2, 3], default: 3 }],
    load: () => import('./tunneltraitors.js'),
  },
  {
    id: 'islandsettlers', name: 'Island Settlers', emoji: '🏝️', color: '#00897b', cat: 'Strategy', tags: ['Trading', 'Building'], min: 2, max: 4,
    tagline: 'Settle the island. Trade, build, outsmart.',
    desc: 'Roll the dice to collect wood, brick, sheep, wheat and ore. Spend them on roads, settlements and cities, trade with friends and the bank, and watch out for the robber. First to the target score rules the island.',
    help: { goal: 'Be the first to reach the target number of victory points (10 by default).', steps: ['Setup: in turn order place a settlement and a road, then place a second pair in reverse order. Your second settlement gives you starting resources.', 'On your turn, roll two dice. Every hex with that number pays out to the settlements (1 card) and cities (2 cards) touching it.', 'Spend resources to build: road 🌲🧱, settlement 🌲🧱🐑🌾 (1 point), city 🌾🌾⛰️⛰️⛰️ (2 points, replaces a settlement), development card 🐑🌾⛰️.', 'Trade with players (make an offer) or with the bank — 4:1, or better with a port.', 'Rolling a 7 moves the robber: players with 8+ cards discard half, and you steal a card from someone next to the robber’s hex.', 'Bonus points: Longest Road (5+ roads, 2 points) and Largest Army (3+ knights, 2 points). Hidden VP cards count too.'], tips: ['Build on 6s and 8s — they roll the most.', 'Ports make trading much cheaper.'] },
    options: [{ key: 'vp', label: 'Points to win', choices: [{ value: 8, label: '8 (quick)' }, { value: 10, label: '10 (standard)' }], default: 10 }],
    load: () => import('./islandsettlers.js'),
  },
  {
    id: 'trickcrew', name: 'Trick Crew', emoji: '🚀', color: '#283593', cat: 'Cards', tags: ['Co-op', 'Trick-taking'], min: 3, max: 5,
    tagline: 'Cooperative trick-taking through space.',
    desc: 'Work together to complete a series of missions. Each mission hands out task cards: a named crew member must win the trick that contains that card. You can’t discuss your hand — you only get one tiny signal each.',
    help: { goal: 'Complete every mission before running out of attempts.', steps: ['Everyone has a hand of coloured cards (1–9) plus four rockets (trump). The player holding the Rocket 4 is the commander and leads.', 'Play tricks like Hearts/Whist: you must follow the suit that was led if you can. Highest card of the led suit wins — unless a rocket is played, then the highest rocket wins.', 'Task cards are shown at the top with a player’s name: that player must win the trick containing that card. If anyone else wins it, the mission fails. Circled numbers mean the tasks must be done in that order.', 'Once per attempt each player may signal: tap a card and choose “highest”, “lowest” or “only one” of its colour — the card is revealed to everyone. Signals can only be sent between tricks.', 'Finish all tasks to complete the mission; fail one and you retry with a fresh deal.'], tips: ['Don’t talk about your cards — only the signal is allowed!', 'Rockets are your power to take over a trick.'] },
    options: [{ key: 'missions', label: 'Missions', choices: [{ value: 4, label: '4 (short)' }, { value: 6, label: '6' }, { value: 10, label: '10 (full)' }], default: 6 }, { key: 'tries', label: 'Attempts per mission', choices: [2, 3, 5], default: 3 }],
    load: () => import('./trickcrew.js'),
  },
  {
    id: 'temple', name: 'Temple Treasure', emoji: '🏺', color: '#bf360c', cat: 'Strategy', tags: ['Push your luck', 'Quick'], min: 2, max: 8,
    tagline: 'Dive deeper for gems — or run before it all collapses.',
    desc: 'Explore a cursed temple together. Each step reveals a card: gems get split between everyone still inside, but two of the same hazard and the whole expedition goes up in smoke. Every step, all explorers secretly decide: press on or race back to camp?',
    help: { goal: 'Have the most treasure after all expeditions.', steps: ['Each expedition, everyone starts inside the temple. A card is revealed each step.', 'Gem cards are split equally among everyone still inside — any leftovers stay on the path.', 'Hazard cards (🕷️🐍🔥🪨🧟) are harmless the first time. When a SECOND card of the same hazard appears, everyone still inside loses all the gems they’re carrying and the expedition ends.', 'After each card, everyone secretly picks: keep exploring, or return to camp. Those who return bank their gems plus an equal share of the gems left on the path.', 'If exactly one explorer returns, they also claim any artifacts on the path (worth 5–12 points each).'], tips: ['Leaving alone is the best way to grab leftover gems and artifacts.', 'Keep an eye on which hazards have already shown up once!'] },
    options: [{ key: 'rounds', label: 'Expeditions', choices: [3, 5], default: 5 }],
    load: () => import('./temple.js'),
  },
  {
    id: 'trainheist', name: 'Train Heist', emoji: '🚂', color: '#c62828', cat: 'Strategy', tags: ['Programming', 'Chaos'], min: 2, max: 6,
    tagline: 'Plan in secret. Watch it all go wrong.',
    desc: 'You’re bandits on a speeding train, out for the loot. Each step, everybody secretly picks an action card; then they all play out in order — punches, shots, climbs and a very angry marshal. Whoever escapes with the most loot wins.',
    help: { goal: 'Finish with the most money. Most shots landed also earns a $1000 gunslinger bonus.', steps: ['The train has cars with a roof and an inside. Loot (purses 💰, jewels 💎, the strongbox 🔒) lies inside; the marshal 👮 patrols inside too.', 'Each round you draw 6 cards. For every step all players secretly choose one card (and its direction/target) — or draw 3 more cards instead.', 'When everyone has locked in, the actions play out in order (reversed on “Switching” steps; “Speeding up” has 2 steps in a row).', 'Move walks between cars, Climb switches roof/inside, Rob grabs loot in your car, Punch makes a bandit in your car drop loot, Shoot hits bandits next door (inside) or along the roof, Marshal moves the sheriff.', 'Getting shot adds a useless Bullet card to your deck. If you end inside the marshal’s car you get shot and flee to the roof.'], tips: ['Cards play out in a fixed order — think about where others will be.', 'Purse values stay secret until the end!'] },
    options: [{ key: 'rounds', label: 'Rounds', choices: [2, 3, 4], default: 3 }],
    load: () => import('./trainheist.js'),
  },
  {
    id: 'redline', name: 'Redline Racers', emoji: '🏎️', color: '#d32f2f', cat: 'Strategy', tags: ['Racing', 'Cards'], min: 2, max: 6,
    tagline: 'Push the engine to the redline — just not past it.',
    desc: 'A card-driven race. Each turn pick a gear, play that many speed cards and zoom around the track. Corners have speed limits: break them and you burn Heat from your engine. Run out and you spin out — and Heat clogs your hand!',
    help: { goal: 'Be the first to complete all the laps.', steps: ['Each turn everyone secretly picks a gear (1–4; a 2-gear jump costs 1 Heat) and plays that many cards from their hand. Total speed = the number of spaces you move.', 'Corners (red circles) have a speed limit. If you pass one going faster, you must pay 1 Heat per point over the limit. No Heat left? You spin out and stop at the corner.', 'Paying Heat puts a dead Heat card in your discard pile, which will clog your hand later. Low gears let you cool down by returning Heat cards from your hand to the engine.', 'Boost: pay 1 Heat to flip an extra card from your deck for bonus speed. Slipstream: finish right behind a rival to get +2 free spaces.'], tips: ['Go fast on the straights, slow into corners.', 'Gear 1–2 is how you recover from overheating.'] },
    options: [{ key: 'laps', label: 'Laps', choices: [1, 2, 3], default: 2 }],
    load: () => import('./redline.js'),
  },
  {
    id: 'sushitrain', name: 'Sushi Train', emoji: '🍣', color: '#ff7043', cat: 'Cards', tags: ['Drafting', 'Quick'], min: 2, max: 8,
    tagline: 'Pick a dish, pass the plate, rack up points.',
    desc: 'A fast card-drafting game. Everyone picks one sushi card from their hand at the same time, then passes the rest to the next player. Collect sets of tempura, sashimi and dumplings, hunt for maki, and save room for pudding!',
    help: { goal: 'Score the most points over three rounds.', steps: ['Everyone secretly picks one card from their hand; then all hands are passed to the player on your left.', 'Rounds end when hands run out. Scoring: 2 Tempura = 5, 3 Sashimi = 10, Dumplings 1/3/6/10/15, Nigiri 1/2/3 (×3 if played on a Wasabi), Maki: most icons 6, second most 3.', 'Chopsticks: once on your plate, you may use them on a later turn to pick two cards — the chopsticks go back into the hand you pass on.', 'Puddings are kept for all three rounds: at the end the most puddings get +6, the fewest −6.'], tips: ['Watch what’s left in the hand you receive to guess what others are collecting.', 'Don’t forget about pudding — it decides close games.'] },
    load: () => import('./sushitrain.js'),
  },
  {
    id: 'onenightwolf', name: 'One Night Wolf', emoji: '🐺', color: '#37474f', cat: 'Bluffing', tags: ['Hidden roles', 'Social'], min: 3, max: 10,
    tagline: 'One night. One chance to find the wolves.',
    desc: 'A lightning-fast hidden-role game. Everyone gets a secret role, the night passes — roles peek and swap cards while you sleep — and then you have one discussion to figure out who the werewolves are. One vote decides it all.',
    help: { goal: 'Village: kill at least one werewolf. Werewolves: survive. Tanner: get yourself killed.', steps: ['Everyone is dealt a secret role card; 3 more cards sit in the centre. Tap your role card to read it (tap again to hide it).', 'Night: roles with powers act in secret — Werewolves and Masons see each other, the Seer peeks, the Robber, Troublemaker and Drunk SWAP cards. The Insomniac checks their final card.', 'Day: discuss! You may claim any role, but remember — your card might have been swapped, so you may not be who you think.', 'Vote: everyone votes for one player. The player with the most votes dies (ties: all die; if everyone gets one vote nobody dies). If the Hunter dies, their vote victim dies too.', 'Village wins if a werewolf dies. Werewolves (and the Minion) win if none do. The Tanner only wins if they are killed.'], tips: ['Use the chat or video to argue — lies are allowed!', 'The first thing to ask: “Who did you wake up as, and what did you see?”'] },
    options: [{ key: 'day', label: 'Discussion time', choices: [{ value: 2, label: '2 min' }, { value: 5, label: '5 min' }, { value: 8, label: '8 min' }], default: 5 }, { key: 'rounds', label: 'Rounds', choices: [1, 3, 5], default: 1 }],
    load: () => import('./onenightwolf.js'),
  },
  {
    id: 'puckfootball', name: 'Puck Soccer', emoji: '⚽', color: '#2e7d32', cat: 'Arcade', tags: ['Real-time', 'Teams'], min: 2, max: 8,
    tagline: 'Top-down soccer with big, bouncy discs.',
    desc: 'A fast HaxBall-style soccer game. You’re a disc with your face on it — bump the ball, line up shots and kick it past the other team. Red vs Blue, automatically balanced, first to the goal limit (or the best score when time runs out) wins.',
    help: { goal: 'Score more goals than the other team before the time is up.', steps: ['Players are split into Red and Blue teams automatically.', 'Move your disc with the arrow keys / WASD, or hold your finger/mouse on the pitch to steer towards that point.', 'Press Space (or the ⚽ button) while touching the ball to kick it hard.', 'Score by getting the ball into the opponent’s goal. First to the goal limit wins; if time runs out the higher score wins (a tie goes to golden goal).'], tips: ['Bumping the ball is gentle — kicking is powerful.', 'On phones the pitch turns vertical so it fills the screen.'] },
    options: [{ key: 'goals', label: 'Goal limit', choices: [3, 5, 10], default: 5 }, { key: 'time', label: 'Match time', choices: [{ value: 2, label: '2 min' }, { value: 3, label: '3 min' }, { value: 5, label: '5 min' }], default: 3 }],
    load: () => import('./puckfootball.js'),
  },
  {
    id: 'tilemosaic', name: 'Tile Mosaic', emoji: '🧩', color: '#0277bd', cat: 'Strategy', tags: ['Drafting', 'Puzzle'], min: 2, max: 4,
    tagline: 'Draft colourful tiles and decorate your palace wall.',
    desc: 'A beautiful tile-drafting game. Take all the tiles of one colour from a workshop, stack them on your pattern lines, and when a line fills up a tile jumps onto your wall. Score for links, complete rows, columns and colours — and don’t let tiles fall on the floor!',
    help: { goal: 'Have the highest score when someone completes a horizontal row on their wall.', steps: ['On your turn tap any tile in a workshop (circle) or the centre. You take ALL tiles of that colour from there; the rest of that workshop slides to the centre.', 'Place the tiles on one of your 5 pattern lines (left) — a line holds only one colour, and only if that colour isn’t already in that row of your wall. Extra tiles fall to the floor and cost points.', 'The first player to take from the centre each round also takes the first-player marker (it costs a floor point).', 'When all tiles are gone, each full pattern line moves one tile onto your wall and scores 1 point plus 1 per tile it links to in its row/column.', 'End bonus: +2 per full row, +7 per full column, +10 per colour with all 5 tiles on the wall.'], tips: ['Taking big groups leaves you with floor penalties — sometimes small is smart.', 'Plan your wall rows so you can link tiles.'] },
    load: () => import('./tilemosaic.js'),
  },
  {
    id: 'pinplace', name: 'Pin the Place', emoji: '📍', color: '#2e7d32', cat: 'Party', tags: ['Geography', 'Quick'], min: 1, max: 10,
    tagline: 'Drop a pin on the world map — closest wins.',
    desc: 'A GeoGuessr-style geography game. Each round a famous landmark, city or natural wonder is named. Zoom into the world map and drop your pin where you think it is. The closer you are, the more points — and clues get easier as the clock ticks.',
    help: { goal: 'Score the most points over all rounds.', steps: ['A place is named at the top. Everyone guesses at the same time.', 'Drag the map to pan, pinch / scroll / use the + − buttons to zoom. Tap to drop your pin (tap again to move it).', 'Press “Lock in guess”. Once everyone has locked in (or time runs out) the answer is revealed.', 'Points depend on distance: a perfect pin is worth 5000 and it falls off with every 1000 km. After a third of the time you get the continent, after two thirds the country’s flag.'], tips: ['Zoom in before you place your pin!', 'Use the continent and flag clues if you’re unsure.'] },
    options: [{ key: 'rounds', label: 'Rounds', choices: [3, 5, 8, 10], default: 5 }, { key: 'time', label: 'Time per round', choices: [{ value: 30, label: '30 sec' }, { value: 45, label: '45 sec' }, { value: 75, label: '75 sec' }], default: 45 }],
    load: () => import('./pinplace.js'),
  },
  {
    id: 'copilots', name: 'Co-Pilots', emoji: '🛬', color: '#0288d1', cat: 'Strategy', tags: ['Co-op', '2 players'], min: 2, max: 2,
    tagline: 'Two pilots, secret dice, one landing.',
    desc: 'A tense two-player cooperative game. You and your co-pilot each roll secret dice and take turns placing them in the cockpit — balancing the plane, controlling engine speed, clearing planes from the approach and readying the landing gear. But you can’t tell each other your numbers!',
    help: { goal: 'Land the plane on the runway (space 6) within 8 rounds without crashing.', steps: ['One of you is the Pilot, the other the Co-pilot. Each round you both roll 4 dice that only you can see.', 'Take turns placing ONE die at a time into a cockpit slot (the Pilot starts). Axis and Engine each have one slot per seat; Radio and Gear slots are shared (you may use at most 2 shared slots per round).', 'Axis: if the two dice differ by 2+, the plane tilts toward the higher die (one step per 2 of difference). More than 2 tilts = crash, and you need to be within ±1 to land.', 'Engines: the two dice are added up: 2–4 moves 1 space, 5–8 moves 2, 9+ moves 3. Moving into a space that still has planes = collision!', 'Radio: a die showing N clears one plane from approach space N. Gear: a die of 3+ readies one landing gear — you need 5 in total by landing.', 'You may talk, but you must not say your dice values!'], tips: ['Clear planes from the spaces you are about to fly through.', 'Plan slow, safe rounds by putting small dice in the engines.'] },
    load: () => import('./copilots.js'),
  },
  {
    id: 'wonderrivals', name: 'Wonder Rivals', emoji: '🏛️', color: '#6d4c41', cat: 'Strategy', tags: ['2 players', 'Civilisation'], min: 2, max: 2,
    tagline: 'Out-build your rival across three ages.',
    desc: 'A head-to-head civilisation duel. Over three ages you take turns drafting cards from a pyramid to collect resources, grow your city, fight for military control and research science — and build wonders with game-changing powers. Win by military, science or points.',
    help: { goal: 'Win by Military supremacy, Scientific supremacy, or have the most points after Age III.', steps: ['Each age, 20 cards are laid out in a pyramid. Only uncovered cards can be taken; face-down cards flip over when uncovered.', 'On your turn tap an available card and choose: Construct it (pay its cost), use it to build one of your Wonders, or Sell it for coins.', 'Costs: coins, or resources your cards produce. Missing resources can be bought from the bank for 2 coins + the number your rival produces (trade cards make this cheaper).', 'Military: red cards push the pawn toward your rival. 3 steps costs them 2 coins, 6 steps costs 5 — and 9 steps wins instantly. Science: 6 different science symbols wins instantly; a pair of the same symbol gives +4 points.', 'Wonders have strong effects (extra turns, destroying cards…). Only 7 wonders can be built in total.', 'End scoring: card & wonder points, 1 point per 3 coins, military bonus, science pairs, guilds.'], tips: ['Watch what your rival needs — taking a card they want can be as good as building it.', 'Cards you don’t need can always be sold for coins.'] },
    load: () => import('./wonderrivals.js'),
  },
  {
    id: 'jigsaw', name: 'Jigsaw Together', emoji: '🧩', color: '#43a047', cat: 'Hangout', tags: ['Co-op', 'Relaxing'], min: 1, max: 10,
    tagline: 'One big puzzle, everyone solving at once.',
    desc: 'A relaxing cooperative jigsaw. Everyone can drag pieces around the same table at the same time — pieces that fit together snap and stay joined. Use a generated picture or upload your own photo for a personal puzzle!',
    help: { goal: 'Complete the whole picture together.', steps: ['The host picks a picture: “Surprise me” generates a colourful scene, or “Use my photo” lets you upload your own. Then press Start.', 'Drag a piece to move it. Drag empty table space to pan the view; pinch, scroll or use the + − buttons to zoom.', 'Bring two matching pieces close together and let go — they snap into place and become one bigger piece.', 'Hold the “Hold to peek” button to see the finished picture. The puzzle is done when everything is one piece!'], tips: ['Edge pieces have a flat side — do the border first.', 'Split up: each person works on a colour or area, then join the chunks.'] },
    options: [{ key: 'pieces', label: 'Pieces', choices: [{ value: 24, label: '24 (easy)' }, { value: 48, label: '48' }, { value: 96, label: '96 (hard)' }], default: 48 }],
    load: () => import('./jigsaw.js'),
  },
  {
    id: 'tshirt', name: 'T-Shirt Showdown', emoji: '👕', color: '#ec407a', cat: 'Drawing', tags: ['Drawing', 'Creative', 'Voting'], min: 3, max: 10,
    tagline: 'Draw it, caption it, mix it, wear it.',
    desc: 'Everyone draws a picture and writes a slogan. Then you mix and match any drawing with any slogan (and any shirt colour) into brand new T-shirts, and the room votes in head-to-head battles for the funniest design.',
    help: { goal: 'Earn the most points from votes on the shirts you make — and on the drawings and slogans you create!', steps: ['Draw a picture for the prompt, then write a short slogan. Repeat for the number of rounds.', 'Mix & match: pick any drawing and any slogan from the pool (yours or others’), choose a shirt colour and make your shirts.', 'Shirts are paired up for head-to-head battles. Everyone not in the battle votes for their favourite.', 'Points: 100 per vote + 100 for the win. You get them if you made the shirt; the artist and the slogan writer each get half!'], tips: ['Odd combinations are usually funniest.', 'Short slogans are easier to read on a shirt.'] },
    options: [{ key: 'shirts', label: 'Designs per player', choices: [1, 2], default: 2 }],
    load: () => import('./tshirt.js'),
  },
  {
    id: 'champdraw', name: 'Champ Draw', emoji: '🥊', color: '#e65100', cat: 'Drawing', tags: ['Drawing', 'Voting', 'Funny'], min: 3, max: 10,
    tagline: 'Draw a champion. Settle it in battle.',
    desc: 'Each player draws a ridiculous champion from a silly title. Then champions are paired up for fights: both players plead why their champion would win a silly challenge, and everyone else votes. Win rounds to reach the grand final!',
    help: { goal: 'Earn the most points from votes. The grand final is worth double!', steps: ['Everyone gets a champion title (like “The Snack Destroyer”) and draws that champion.', 'Each round, champions are paired up and given a challenge (e.g. “Who would win a dance battle?”). Both players write a short plea.', 'Everyone else votes for who would win. 100 points per vote plus 100 for the win.', 'After the rounds, the top two champions meet in the grand final — worth double points, with everybody voting.'], tips: ['Funny pleas beat serious ones.', 'The champion’s drawing matters too — make it memorable!'] },
    options: [{ key: 'rounds', label: 'Battle rounds', choices: [1, 2, 3], default: 2 }],
    load: () => import('./champdraw.js'),
  },
  {
    id: 'alienamong', name: 'Alien Among Us', emoji: '👽', color: '#2e7d32', cat: 'Bluffing', tags: ['Hidden roles', 'Social', 'Funny'], min: 4, max: 10,
    tagline: 'Everyone answers a question. Aliens got a different one.',
    desc: 'A spaceship party game of subtle suspicion. Everybody answers a question, but the secret aliens were given a slightly different question! Compare the answers, argue it out, and vote the suspects out of the airlock before the aliens take over.',
    help: { goal: 'Humans: eject all the aliens. Aliens: survive until they equal the number of humans.', steps: ['Tap your role card: Human or Alien (aliens see who the other aliens are).', 'Everyone answers a short question. Humans all get the same question — aliens get a similar but different one, so their answers will be a bit “off”.', 'All answers are shown with names. Discuss in chat or by voice — who answered a different question?', 'Everyone votes for a suspect. The player with the most votes (at least 2) is ejected and their role is revealed.', 'Repeat with a new question until all aliens are gone (humans win) or the aliens match the humans (aliens win).'], tips: ['Aliens: keep answers short and vague so you can’t be pinned down.', 'Humans: ask “why did you say that?” — aliens are bad at explaining.'] },
    load: () => import('./alienamong.js'),
  },
  {
    id: 'connect4',
    name: 'Connect Four',
    emoji: '🔴',
    color: '#3b5bff',
    cat: 'Board',
    tags: ['Classic'],
    min: 2,
    max: 2,
    tagline: 'Drop discs, line up four.',
    desc: 'The classic head-to-head. Take turns dropping discs into the grid — first to line up four in a row wins.',
    howto: [
      'Click a column to drop your disc.',
      'Connect four of your discs horizontally, vertically or diagonally to win.',
      'If the board fills up, it’s a draw.',
    ],
    load: () => import('./connect4.js'),
  },
];


// Extra help shown in the rules sheet (the ? button): controls + tips. Merged into each game's `help`.
const EXTRA_HELP = {
  sketch: { controls: [['Drag', 'draw'], ['Colour dots', 'pick a colour'], ['Bucket', 'fill an area'], ['Type + Enter', 'guess the word']], tips: ['Fast guesses score the most — keep typing!', 'Close guesses say “so close” only to you.'] },
  beans: { controls: [['Tap a field', 'plant the highlighted card'], ['Harvest', 'cash in a field'], ['Prices', 'bean price chart']], tips: ['You can never rearrange your hand — trade away what blocks you.', 'Donating a card to someone who needs it makes friends (and favours).'] },
  pool: { controls: [['Drag on table', 'aim'], ['Slider', 'set power'], ['Space / Shoot', 'take the shot'], ['Drag cue ball', 'place it (ball in hand)']], tips: ['The dotted line shows where the cue ball will hit first.'] },
  colorrush: { controls: [['Tap a card', 'play it'], ['DRAW pile', 'draw a card'], ['UNO!', 'call it on your last card']], tips: ['Tap “Catch!” fast when an opponent forgets to call UNO.'] },
  poker: { controls: [['Fold / Check / Call', 'your options'], ['Slider', 'choose a bet'], ['All-in', 'push every chip']], tips: ['You have 40 seconds per action.'] },
  chess: { controls: [['Tap a piece', 'see its legal moves'], ['Tap a square', 'move there']], tips: ['Pawns reaching the last rank can promote.'] },
  liars: { controls: [['− / +', 'quantity'], ['Dice faces', 'the number you bid on'], ['Bid / Liar!', 'your action']], tips: ['1s are wild unless you bid on 1s.'] },
  bomber: { controls: [['Arrows / WASD', 'move'], ['Space', 'drop a bomb']], tips: ['Phones: use the on-screen pad and bomb button.', 'Your own bombs can hurt you!'] },
  tanks: { controls: [['Arrows / WASD', 'drive'], ['Space', 'fire']], tips: ['Bullets cancel each other out.'] },
  snake: { controls: [['Arrows / WASD / swipe', 'steer']], tips: ['Crashed snakes drop apples for the survivors.'] },
  blocks: { controls: [['← →', 'move'], ['↑ or X', 'rotate'], ['Z', 'rotate back'], ['↓', 'soft drop'], ['Space', 'hard drop'], ['C', 'hold']], tips: ['The red bar beside your board shows incoming garbage.'] },
  sumo: { controls: [['Arrows / WASD / hold finger', 'move'], ['Space / dash button', 'dash']], tips: ['The platform shrinks after 10 seconds.'] },
  pong: { controls: [['Arrows / drag', 'move your paddle']], tips: ['Hit the ball with the edge of the paddle to steer it.'] },
  typeracer: { controls: [['Type', 'the passage as fast as you can']], tips: ['Fix red letters before you can continue.'] },
  imposter: { controls: [['Tap your card', 'peek at your word']], tips: ['Be vague enough that the imposter can’t guess — but specific enough to be trusted.'] },
  wordspies: { controls: [['Tap a card', 'select it'], ['Tap again', 'flip it']], tips: ['The assassin card ends the game for your team.'] },
  retro: { controls: [['Arrows', 'D-pad'], ['X', 'A button'], ['Z', 'B button'], ['Enter', 'Start'], ['C / Shift', 'Select']], tips: ['Only play games you own.'] },
  movie: { controls: [['Share my screen', 'start presenting'], ['Emoji', 'react']], tips: ['Use headphones to avoid echo.'] },
  connect4: { controls: [['Tap a column', 'drop a disc']], tips: ['Watch for diagonals!'] },
};
for (const g of GAMES) g.help = { ...(EXTRA_HELP[g.id] || {}), ...(g.help || {}) };

// Home-screen order: the requested line-up first (in order), then the Jackbox-style games, then the originals
const ORDER = ['telephone', 'wordspies', 'captions', 'rowrumble', 'sketch', 'dialitin', 'petals', 'drawbattle', 'uniqueclues', 'wordbomb', 'spyplace', 'codecrack', 'shadowquest', 'royalletters', 'tunneltraitors', 'islandsettlers', 'trickcrew', 'temple', 'trainheist', 'letterdash', 'redline', 'sushitrain', 'onenightwolf', 'puckfootball', 'tilemosaic', 'pinplace', 'copilots', 'wonderrivals', 'jigsaw', 'colorrush', 'quipclash', 'tshirt', 'triviatrap', 'fibquiz', 'champdraw', 'alienamong', 'movie', 'beans', 'pool', 'poker', 'chess', 'liars', 'imposter', 'bomber', 'tanks', 'snake', 'blocks', 'sumo', 'pong', 'typeracer', 'retro', 'connect4'];
GAMES.sort((a, b) => ORDER.indexOf(a.id) - ORDER.indexOf(b.id));

export const GAME_BY_ID = Object.fromEntries(GAMES.map((g) => [g.id, g]));
